### ISSUE TITLE
Can this be updated to work with lovelace-auto-entities?

### ISSUE THREAD

**Issue by mmartoccia** [benct/lovelace-battery-entity-row#2]
This would be an excellent complement to the auto-entities card for all batteries within the HA system.

**Comment by benct** [comment]
If I've understood correctly, auto-entities is designed to automatically fill a `entities` field with entities that match a criteria, but this card is a single `entity-row` with no field for `entities`..

However, I think it should in theory work with something like:
```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - name: <match your battery entities>
      options:
        type: custom:battery-entity-row
        <battery-entity-row options>
```
